//Users Types
export const SET_POST_JOURNAL = 'SET_POST_JOURNAL';
export const POST_JOURNAL_PENDING = 'POST_JOURNAL_PENDING';
export const POST_JOURNAL_ERROR = 'POST_JOURNAL_ERROR';

export const GET_ALL_JOURNAL = 'GET_ALL_JOURNAL';
export const GET_ALL_JOURNAL_PENDING = 'GET_ALL_JOURNAL_PENDING';
export const GET_ALL_JOURNAL_ERROR = 'GET_ALL_JOURNAL_ERROR';

//***** */

export const GET_SINGLE_JOURNAL = 'GET_ALL_JOURNAL';
export const GET_SINGLE_JOURNAL_PENDING = 'GET_ALL_JOURNAL_PENDING';
export const GET_SINGLE_JOURNAL_ERROR = 'GET_ALL_JOURNAL_ERROR';

export const DELETE_JOURNAL = 'DELETE_JOURNAL';
export const DELETE_JOURNAL_PENDING = 'DELETE_JOURNAL_PENDING';
export const DELETE_JOURNAL_ERROR = 'DELETE_JOURNAL_ERROR';

//*** */

export const UPDATE_JOURNAL = 'UPDATE_JOURNAL';
export const UPDATE_JOURNAL_PENDING = 'UPDATE_JOURNAL_PENDING';
export const UPDATE_JOURNAL_ERROR = 'UPDATE_JOURNAL_ERROR';
