//Users Types
export const SET_POST_JOURNAL = 'SET_POST_JOURNAL';
export const POST_JOURNAL_PENDING = 'POST_JOURNAL_PENDING';
export const POST_JOURNAL_ERROR = 'POST_JOURNAL_ERROR';

export const GET_ALL_JOURNAL = 'GET_ALL_JOURNAL';
export const GET_ALL_JOURNAL_PENDING = 'GET_ALL_JOURNAL_PENDING';
export const GET_ALL_JOURNAL_ERROR = 'GET_ALL_JOURNAL_ERROR';
